### ISSUE TITLE
Can't install win32gui

### ISSUE THREAD

**Issue by CoconutMacaroon** [CoconutMacaroon/Cinematic-Meeting-Sign#4]
**Describe the bug**
Can't install `win32gui` via `pip install win32gui` on Anaconda with Python 3.8.2

**How can I  reproduce this bug**
Create a blank Python 3.8.2 Anaconda environment. In that environment, run the command `pip install win32gui`.

**What should have happened?**
`pip` should have installed `win32gui` without any issues.

**What is the error message?**
![Annotation 2020-05-01 084108](https://user-images.githubusercontent.com/45187468/80818912-dabf3a80-8b88-11ea-9ba3-672a591fa61f.png)

**Comment by primus1a** [comment]
Any solution? Same problem here on windows 10 .

**Comment by CoconutMacaroon** [comment]
## My research

Sadly, I haven't gotten it to work on the current version of Python. I found this https://stackoverflow.com/questions/52806906/cant-install-win32gui and tried that solution (in a Python 3.6 Anaconda environment), and it worked.

## Solution (maybe)

However, answering your original question: try downloading Python 3.6 (rather than the latest Python), and see if that fixes it. Let me know if that works.

**Comment by CoconutMacaroon** [comment]
@primus1a Did that fix the problem?

**Comment by CoconutMacaroon** [comment]
Fixed. Download python 3.6.X instead of the latest version as a fix.
